{{- if eq .Values.metrics.enabled true -}}
  {{- if .Values.global.newrelic.enabled -}}
    {{- range $teamName, $teamInfo := .Values.global.newrelic.teams }}
      {{- if ne $teamInfo.ignore true -}}
        {{- if and (not $teamInfo.licenseKey.secretRef) $teamInfo.licenseKey.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nrotel.statefulsetName" $ }}-{{ $teamName }}
  namespace: {{ $.Release.Namespace }}
data:
  licenseKey: {{ $teamInfo.licenseKey.value | b64enc }}
---
        {{- end -}}
      {{- end -}}
    {{- end -}}
  {{- else -}}
    {{- range $teamName, $teamInfo := .Values.statefulset.newrelic.teams }}
      {{- if ne $teamInfo.ignore true -}}
        {{- if and (not $teamInfo.licenseKey.secretRef) $teamInfo.licenseKey.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nrotel.statefulsetName" $ }}-{{ $teamName }}
  namespace: {{ $.Release.Namespace }}
data:
  licenseKey: {{ $teamInfo.licenseKey.value | b64enc }}
---
        {{- end -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
